[package]
name = "spreading_colors_ca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "1.0.10"
colored = "2.0.0"
image = "0.24.4"
inquire = "0.5.2"
rand = "0.8.5"
